name: Bug Report
description: File a bug report.
title: "StateCraft: "
labels: [StateCraft]
projects: ["ZCrewSoftware/ZCrew.Common"]
type: bugfix
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      value: None.
    validations:
      required: false
