name: Spike
description: Exploratory work to create a proof of concept
title: "StateCraft: "
labels: []
projects: ["ZCrewSoftware/ZCrew.StateCraft"]
type: spike
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of problem you're facing.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of the solution you'd like.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      value: None.
    validations:
      required: false
